import { View, Text } from 'react-native'
import React from 'react'

export const fontFamily ={
 aBold: 'Axiforma-Bold',
 aExtraB: 'Axiforma-ExtraBold',
 aHeavy: 'Axiforma-HeavyItalic',
 aMedium: 'Axiforma-Medium',
 aSemiBold: 'Axiforma-SemiBold',
 aRegular: 'Axiforma-Regular',
 rBold: 'Raleway-Bold',
 rExtraB: 'Raleway-ExtraBold',
 rExtraL: 'Raleway-ExtraLight',
 rLight: 'Raleway-Light',
 rMedium: 'Raleway-Medium',
 rRegular: 'Raleway-Regular',
 rSemiB: 'Raleway-SemiBold',
 rHeavy: 'Raleway-Heavy',
 iBold:'Inter-Bold',
 iExtraB:'Inter-ExtraBold',
 iExtraL:'Inter-ExtraLight',
 iLight:'Inter-Light',
 iMedium:'Inter-Medium',
 iRegular:'Inter-Regular',
 iSemiB:'Inter-SemiBold',
 iThin:'Inter-Thin',
 iBlack: 'Inter-Black'
};
export const fontSize ={
    font10: 10,
    font12: 12,
    font14: 14,
    font15: 15,
    font16: 16,
    font17: 17,
    font18: 18,
    font20: 20,
    font22: 22,
    font30: 30,
}
export const color={
    white: '#FFFFFF',
    darkBlack: '#242424',
    black:'#000000',
    darkGray:' #56514B',
    darkGray2:'rgba(15, 15, 15, 0.75)',
    gray:'#808080',
    lightPink:'rgba(87, 42, 200, 0.1)',
    mediumBlack:'#545454',
    lightGray:'#F5F5F5',
    mediumGray:'#D3D3D3',
    medBlack:'#0F0F0F',
    getgray:'rgba(15, 15, 15, 0.5)',
    searchBarIcon:'rgba(15, 15, 15, 0.4)',
    lightPurple:'#E2D9FA',
    lightBlue:'#F3F4F6',
    green: '#007500',
    gray7575:'#757575',
    purple:'#6E42E5',
    medPurple:'#572AC8',
    menuBtn:'#262626',
    searchBorder:'rgba(15, 15, 15, 0.2);'

}
export const lineHeight ={
    line015 : 15.84,
    line016 : 16.04,
    line22: 22,
    line16: 16,
    line24 : 24,
    line19 : 19,
    line019 : 19.25,
    line20: 20,
    line23: 23
}
export const image={
    // Accounts : require('../assets/images/Accounts.png'),
    AcRepair : require('../assets/images/Ac-Repair.png'),
    Uc : require('../assets/images/Active.png'),
    Adidas : require('../assets/images/adias.png'),
    Bleach : require('../assets/images/Bleach&Detan.png'),
    Bookings : require('../assets/images/Boookings.png'),
    UcPlus : require('../assets/images/Group6.png'),
    Cleanup : require('../assets/images/Cleanup.png'),
    Frameseller : require('../assets/images/Frameseller.png'),
    CleaningPest : require('../assets/images/fuel.png'),
    Facial : require('../assets/images/GlowFacilas.png'),
    Accounts : require('../assets/images/Group.png'),
    HeadMessage : require('../assets/images/Head-message.png'),
    HeirCare : require('../assets/images/Heir-care.png'),
    HomeRepair : require('../assets/images/Home-Repair.png'),
    WomenSalon : require('../assets/images/image2.png'),
    MenMessage : require('../assets/images/light.png'),
    Heirs : require('../assets/images/heirs.png'),
    Heir : require('../assets/images/heirs.png'),
    ArrowLeft :require('../assets/images/aarowleft.png'),
    roundStar:require('../assets/images/Round_Blue.png'),
    SkyBox:require('../assets/images/SkyBox.png'),
    Star:require('../assets/images/Star.png'),
    HeirSkin:require('../assets/images/new.png'),
    MenSalon:require('../assets/images/pro.png'),
    Eplumbing:require('../assets/images/tool.png'),
    HomePainting:require('../assets/images/sale.png'),
    TvInstall:require('../assets/images/Tv-repair.png'),
    CredPay:require('../assets/images/credpay.png'),
    CredPay2:require('../assets/images/credpay2.png'),
    Gpay:require('../assets/images/gpay.png'),
    PhonePay:require('../assets/images/phonepay.png'),
    Waxing:require('../assets/images/Waxing.png'),
    Pedicure:require('../assets/images/Pedicure.png'),
    SpecialFacial:require('../assets/images/SpecializedFacials.png')
}
export const style ={
    weight400:{
    fontFamily: fontFamily.aSemiBold,
    fontSize: fontSize.font14,
    lineHeight: lineHeight.line23,
    color: color.darkBlack}
}
